import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
         <body>
        <header className="bg-yellow-400 p-2 my-2">Header</header>
        <main className="flex p-4">{children}</main>
        <footer className="bg-cyan-400 p-2 my-2">Footer</footer>
      </body>
    </html>
  );
}
